{% set name = "nannyml" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nannyml-{{ version }}.tar.gz
  sha256: 5a810b120e0b3e5d623909b7e4276ef719275bff6647bc90cecf2ddffd17cf6b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7.1
  run:
    - category_encoders >=2.3.0
    - click >=8.1.3
    - gcsfs >=2022.5.0
    - jinja2 <3.1
    - joblib >=1.1.0
    - matplotlib-base >=3.5.1
    - numpy <1.23.0,>=1.16.5
    - pandas >=1.3.0
    - plotly >=5.6.0
    - pyarrow <9.0.0,>=8.0.0
    - pydantic ==1.9.1
    - pyfiglet >=0.8.post1
    - python >=3.7.1
    - python-dateutil >=2.8.2
    - python-kaleido ==0.2.1
    - pyyaml >=6.0
    - rich >=12.5.1
    - scikit-learn >=1.0.2
    - scipy ~=1.7.3
    - seaborn >=0.11.2

test:
  imports:
    - nannyml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nannyml/nannyml
  doc_url: https://nannyml.readthedocs.io/en/stable/
  summary: NannyML, Your library for monitoring model performance.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nnansters
    - thewchan
